# -*- coding: utf-8 -*-
"""Futureintern_DA_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AU6aiZ-a_D-V6j4Cl2VV9HSwHxJnJrM_
"""

import pandas as pd
import numpy as np

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
gender_submission = pd.read_csv('gender_submission.csv')

train_data.head()

test_data.head()

#check data type
train_data.dtypes

#check data type
test_data.dtypes

#identify categorical column
categorical_column = train_data.select_dtypes(include=['object','category']).columns.tolist()

#identify numerical column
numerical_column = train_data.select_dtypes(include=['int64','float64']).columns.tolist()

#identify categorical column
categorical_column = test_data.select_dtypes(include=['object','category']).columns.tolist()

#identify numerical column
numerical_column = test_data.select_dtypes(include=['int64','float64']).columns.tolist()

print("categorical column:")
print(categorical_column)

print("numerical column:")
print(numerical_column)

print("categorical column:")
print(categorical_column)

print("numerical column:")
print(numerical_column)

column_used=['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
selected_column= train_data.loc[:, column_used]

selected_column.head()

column_means = selected_column.mean()
print("mean for each column:" ,column_means)

#mode
column_modes = selected_column.mode()
print("mode for each column:" ,column_modes)

#median
column_median = selected_column.median()
print("median for each column:" ,column_median)

column_std_deviation = selected_column.std()
print("std_deviation for each column:" ,column_std_deviation)

#check for statistics for each numeric column all togather\
selected_column.describe()

#now we take origional dataset andcheck for more stats data
train_data.head()